name: Build PixelOS for A73xq

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      USE_CCACHE: true
      CCACHE_DIR: ${{ github.workspace }}/.ccache
      RCLONE_CONFIG: ${{ secrets.RCLONE_CONF }}

    steps:
    - name: Setup dependencies
      run: |
        sudo apt update
        sudo apt install -y openjdk-11-jdk git curl repo gcc g++ python3 \
            bc bison build-essential zip curl zlib1g-dev \
            libncurses5-dev libncurses5 libncurses-dev \
            libssl-dev flex lib32ncurses5-dev x11proto-core-dev \
            libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils \
            xsltproc unzip fontconfig lzop lz4 ccache

    - name: Setup ccache
      uses: actions/cache@v3
      with:
        path: ${{ env.CCACHE_DIR }}
        key: ccache-${{ github.run_id }}
        restore-keys: |
          ccache-

    - name: Initialize repo and sync source
      run: |
        mkdir pixelos && cd pixelos
        repo init -u https://github.com/PixelOS-AOSP/manifest.git -b fifteen --git-lfs
        repo sync

    - name: Clone device, vendor, kernel trees
      run: |
        cd pixelos
        git clone https://github.com/LineageOS/android_hardware_samsung hardware/samsung
        git clone https://github.com/LineageOS/android_device_samsung_a73xq.git device/samsung/a73xq
        git clone https://github.com/Simon1511/android_device_samsung_sm7325-common device/samsung/sm7325-common
        git clone https://github.com/Simon1511/android_vendor_samsung_a73xq.git vendor/samsung/a73xq
        git clone https://github.com/Simon1511/android_vendor_samsung_sm7325-common vendor/samsung/sm7325-common
        git clone https://github.com/LineageOS/android_kernel_samsung_sm7325.git kernel/samsung/sm7325
        
    - name: Build PixelOS
      run: |
        cd pixelos
        export CCACHE_EXEC=$(which ccache)
        ccache -M 20G
        source build/envsetup.sh
        lunch aosp_a73xq-bp1a-userdebug
        mka bacon

    - name: Check if ROM exists before upload
      run: |
        if ls pixelos/out/target/product/a73xq/*.zip 1> /dev/null 2>&1; then
          echo "ROM found, proceeding with upload."
        else
          echo "No ROM found. Exiting."
          exit 1
        fi

    - name: Upload ROM to Google Drive via rclone
      run: |
        sudo apt install -y rclone
        echo "${RCLONE_CONFIG}" > rclone.conf
        cd pixelos
        rclone --config=rclone.conf copy out/target/product/a73xq/*.zip gdrive:/PixelOS-a73xq/

    - name: Save ROM as GitHub Artifact (backup)
      uses: actions/upload-artifact@v3
      with:
        name: PixelOS-a73xq
        path: pixelos/out/target/product/a73xq/*.zip
